#!/usr/bin/env python3
"""
Generate CARD_FILL_IN.txt — a plain-text sheet for authoring the cards that
are still dark.

Generated, not written by hand. The hand-written version of this file drifted:
it went on saying "13 cards, 0 live" and naming a signer the owner had not
agreed to, while five cards were signed and carrying traffic. A sheet that
disagrees with the card files about what is live is worse than no sheet.

LIVE CARDS ARE OMITTED. This sheet only ever lists what is still outstanding,
so anything in it is genuinely unwritten. Re-run after every authoring pass:

    cd server && python3 gen_card_fill_in.py
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import vent_module as vm  # noqa: E402

RULE = "=" * 72
THIN = "-" * 72

FAMILY_HEADER = {
    "physiology": "FAMILY 1 — PHYSIOLOGY (initial settings)",
    "troubleshooting": "FAMILY 2 — TROUBLESHOOTING (alarms / decompensation)",
    "device": ("FAMILY 3 — DEVICES (authored summary only — never manual "
               "text, {n} char max per field)"),
}

SETTINGS_KEYS = ("mode", "vt_ml_per_kg_ibw", "rate_strategy", "peep", "fio2")
PARAM_KEYS = ("mode", "tidal_volume", "rate", "peep", "fio2", "alarm_limits")

BLANK = "<>"


def _lines(L, field, help_text, n=1):
    L.append(f"{field}:  ({help_text})")
    for _ in range(n):
        L.append(f"  {BLANK}")
    L.append("")


def physiology_body(L, card):
    L.append("initial_settings:")
    for k in SETTINGS_KEYS:
        L.append(f"  {k}: {BLANK}")
    L.append("")
    _lines(L, "titrate_on", "what you adjust against, in order — one per line")
    _lines(L, "watch_for", "monitoring lines — one per line")
    _lines(L, "evac_if", "threshold triggers — one per line")
    _lines(L, "escape_hatch", 'the "this assumes X" line — shown on every serve')
    _lines(L, "actual_weight_caveat",
           "shown ONLY when height is missing and VT came off actual weight")
    _lines(L, "tldr", "one line, what the medic reads first")


def troubleshooting_body(L, card):
    L.append("steps:  (ordered; step 1 is the fork. add as many blocks as you need)")
    for i in (1, 2, 3):
        L.append(f"  {i}. check:  {BLANK}")
        L.append(f"     finding: {BLANK}")
        L.append(f"     action:  {BLANK}")
    L.append("")
    _lines(L, "watch_for", "monitoring lines — one per line")
    _lines(L, "evac_if", "threshold triggers — one per line")
    _lines(L, "escape_hatch", 'the "this assumes X" line — shown on every serve')
    _lines(L, "tldr", "one line, what the medic reads first")


def device_body(L, card):
    _lines(L, "startup_sequence",
           "power-on to delivering a breath, one step per line")
    L.append("parameter_map:  (where each setting lives in that UI)")
    for k in PARAM_KEYS:
        L.append(f"  {k}: {BLANK}")
    L.append("")
    L.append("alarm_table:  (display text | meaning | first action, one per line)")
    L.append(f"  {BLANK} | {BLANK} | {BLANK}")
    L.append("")
    _lines(L, "quirks", "battery/O2, altitude, field gotchas — one per line")
    _lines(L, "crosswalk",
           "how to enter a physiology card's settings on this device")
    L.append("manual_reference:")
    for k in ("title", "revision", "verified_date"):
        L.append(f"  {k}: {BLANK}")
    L.append("")


BODY = {"physiology": physiology_body,
        "troubleshooting": troubleshooting_body,
        "device": device_body}


def main():
    live = vm.servable_cards()
    total = sum(len(c) for c in vm.FAMILIES.values())
    done = sum(len(v) for v in live.values())
    dark = {f: sorted(c for c in vm.FAMILIES[f] if c not in live[f])
            for f in vm.FAMILIES}

    L = []
    L.append("VENTILATOR CARD CONTENT — FILL-IN SHEET")
    L.append(f"{total} cards, {done} live. This sheet lists ONLY the "
             f"{total - done} still outstanding.")
    L.append("Fill under each field; leave a card blank to skip it.")
    L.append(f"Lists: one item per line. Anything left as {BLANK} stays unsigned.")
    L.append("")
    L.append("Signer: a credentialed clinician. Set reviewed_by to the exact")
    L.append("string, review_date to the day you signed, signoff true, version 1.0.0.")
    L.append("")
    L.append("A signed card must carry NO PENDING_CLINICAL_SIGNOFF in any field —")
    L.append("including actual_weight_caveat and tldr, which the engine's gate does")
    L.append("not check. test_no_signed_card_kept_a_sentinel_anywhere catches those.")
    L.append("")
    L.append("Generated by server/gen_card_fill_in.py — re-run it, do not hand-edit.")
    L.append("")

    if done:
        L.append(f"ALREADY LIVE, not listed below ({done}):")
        for family in ("physiology", "troubleshooting", "device"):
            for card_id in live[family]:
                card = vm.FAMILIES[family][card_id]
                L.append(f"  {card_id} v{card.get('version')} — "
                         f"reviewed {card.get('reviewed_by')}, "
                         f"{card.get('review_date')}")
        L.append("")

    for family in ("physiology", "troubleshooting", "device"):
        if not dark[family]:
            continue
        L.append(RULE)
        header = FAMILY_HEADER[family].format(n=vm.DEVICE_FIELD_MAX_CHARS)
        L.append(header)
        L.append(RULE)
        L.append("")
        for card_id in dark[family]:
            card = vm.FAMILIES[family][card_id]
            servable, reason = vm.card_is_servable(card, family)
            L.append(THIN)
            L.append(f"CARD: {card_id}   ({card.get('title')})")
            L.append(THIN)
            L.append(f"  not live: {reason}")
            L.append(f"  routes on: {', '.join(card.get('applies_when', []))}")
            note = card.get("_authoring_note")
            if note:
                L.append(f"  note: {note}")
            L.append("")
            BODY[family](L, card)
            _lines(L, "references",
                   "at least ONE required — engine refuses a card with none")
            L.append("")

    out = pathlib.Path(__file__).resolve().parent.parent / "CARD_FILL_IN.txt"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} — {total - done} cards outstanding, {done} live and omitted")


if __name__ == "__main__":
    main()
