#!/usr/bin/env python3
"""
Generate CARD_CONTENT_WORKSHEET.md from the card files and the engine schema.

Generated, not written by hand, so it cannot drift from what the engine
actually requires. Re-run it after every authoring pass:

    cd server && python3 gen_card_worksheet.py
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import vent_module as vm  # noqa: E402

FAMILY_TITLE = {
    "physiology": "Family 1 — Physiology cards (initial settings)",
    "troubleshooting": "Family 2 — Troubleshooting cards (alarms / decompensation)",
    "device": "Family 3 — Device cards (four field ventilators)",
}

FIELD_HELP = {
    "initial_settings": "mode, vt_ml_per_kg_ibw, rate_strategy, peep, fio2",
    "titrate_on": "what you adjust against, in order",
    "watch_for": "monitoring lines",
    "evac_if": "threshold triggers",
    "escape_hatch": 'the "this assumes X" line — shown on every serve',
    "actual_weight_caveat": "shown ONLY when height/sex are missing and VT is on actual weight",
    "tldr": "one sentence: the most critical action or number",
    "steps": "ordered check → finding → action; step 1 is the fork",
    "startup_sequence": "power-on to delivering a breath",
    "parameter_map": "where each setting lives in that UI",
    "alarm_table": "display text → meaning → first action",
    "quirks": "battery/O2 behaviour, altitude, known field gotchas",
    "crosswalk": "how to enter a physiology card's settings on this device",
    "manual_reference": "title, revision, verified_date — cited, never reproduced",
}


def pending_fields(card, family):
    schema = vm._FAMILY_SCHEMA[family]
    out = []
    for field in schema["clinical"]:
        if vm._is_pending(card.get(field)):
            out.append(field)
    for field in ("references", "reviewed_by", "review_date"):
        if vm._is_pending(card.get(field)):
            out.append(field)
    if family == "device" and vm._is_pending(card.get("manual_reference")):
        out.append("manual_reference")
    return out


def main():
    live = vm.servable_cards()
    total = sum(len(c) for c in vm.FAMILIES.values())
    done = sum(len(v) for v in live.values())

    L = []
    L.append("# Ventilator cards — content worksheet")
    L.append("")
    L.append("**Author: a credentialed clinician. Nobody else signs a card.**")
    L.append("")
    L.append("Generated by `server/gen_card_worksheet.py` from the card files and "
             "the engine schema, so it cannot drift from what the engine actually "
             "requires. Re-run it after every authoring pass.")
    L.append("")
    L.append(f"**{done} of {total} cards live.**")
    L.append("")
    L.append("## How a card goes live")
    L.append("")
    L.append("Cards deploy **one at a time**. Partial deployment is the normal "
             "state, not a migration step — an unsigned card is invisible to the "
             "pipeline and the query falls through to whatever answered it before.")
    L.append("")
    L.append("1. Fill every field listed for that card below.")
    L.append("2. Add at least one entry to `references` — the engine refuses a "
             "card with none.")
    L.append("3. Set `reviewed_by` to exactly `clinician` and `review_date` to "
             "the date you signed it.")
    L.append("4. Set `signoff` to `true`.")
    L.append("5. Bump `version`.")
    L.append("6. `cd server && python3 -m pytest test_vent_module.py -q` — the "
             "fence tests should still pass, and that card starts carrying traffic.")
    L.append("")
    L.append("The engine refuses to serve a card that is signed while any "
             "clinical field is still empty or `PENDING_CLINICAL_SIGNOFF`, so a "
             "half-filled card cannot reach a medic by accident. There is no "
             "override — `EDGECDSS_DEBUG_WARN_ONLY` does not reach this gate.")
    L.append("")
    L.append("## What is NOT yours to fill")
    L.append("")
    L.append("`applies_when` is dispatch vocabulary, pre-filled so the routing "
             "tests have something to assert. Review it — a wrong signal sends a "
             "real query to the wrong card — but it is not clinical content.")
    L.append("")
    L.append("`id`, `title`, `version`, `source_label` are structural.")
    L.append("")

    for family in ("physiology", "troubleshooting", "device"):
        L.append(f"## {FAMILY_TITLE[family]}")
        L.append("")
        if family == "device":
            L.append("> **Copyright rule, enforced not advised.** Device card "
                     "content is YOUR AUTHORED SUMMARY referencing each "
                     "manufacturer's operator manual. Never reproduced manual "
                     "text, no verbatim passages, no figures. No content field "
                     f"may exceed {vm.DEVICE_FIELD_MAX_CHARS} characters, and "
                     "`lint_device_cards()` flags any field sharing a "
                     "60-character verbatim run with manual text. Manuals must "
                     "not be committed — `.manual.` and `manuals/` are in "
                     "`.gitignore`.")
            L.append("")
        for card_id in sorted(vm.FAMILIES[family]):
            card = vm.FAMILIES[family][card_id]
            servable, reason = vm.card_is_servable(card, family)
            mark = "x" if servable else " "
            L.append(f"### [{mark}] `{card_id}` — {card.get('title')}")
            L.append("")
            L.append(f"*Version {card.get('version')} · "
                     f"{'LIVE' if servable else 'not live: ' + reason}*")
            L.append("")
            note = card.get("_authoring_note")
            if note:
                L.append(f"> {note}")
                L.append("")
            fields = pending_fields(card, family)
            if not fields:
                L.append("Nothing outstanding.")
            else:
                for f in fields:
                    help_text = FIELD_HELP.get(f, "")
                    L.append(f"- [ ] `{f}`" + (f" — {help_text}" if help_text else ""))
            L.append("")

    L.append("## When every card is live")
    L.append("")
    L.append("Run the harness against the branch and compare to the round-1 "
             "baseline. The F-12 measurement to beat: **0 of 4 DKA vent "
             "phrasings returned any of VT / RR / PEEP / FiO2, against 4 of 4 "
             "for TBI.**")
    L.append("")
    L.append("```")
    L.append("cd server && python3 -m pytest test_vent_module.py -q")
    L.append("python3 gen_card_worksheet.py    # refresh this file")
    L.append("```")

    out = pathlib.Path(__file__).resolve().parent.parent / "CARD_CONTENT_WORKSHEET.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} — {done}/{total} cards live")


if __name__ == "__main__":
    main()
